# Generated by Django 5.1.4 on 2025-01-16 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_device_user_delete_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.UUIDField(null=True, verbose_name='device UUID')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login')),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'WEB'), (2, 'ANDROID'), (3, 'IOS')], default=1)),
                ('device_os', models.CharField(max_length=20, null=True, verbose_name='device os')),
                ('device_model', models.CharField(max_length=20, null=True, verbose_name='device model')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
