# Generated by Django 5.1.4 on 2025-01-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Pdf')], default=2, verbose_name='Type file: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='file',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
